name: 🚀 Tarea de Despliegue

on:
   push:
    
jobs:
  deploy:
    name: 🎉 Trabajo de Despliegue
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Obteniendo el código más reciente
        uses: actions/checkout@v4

      - name: 📂 Sincronizando archivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:  ftp-yesidsan.alwaysdata.net # Change if using another host
          username: yesidsan
          password: Cc14635767 
          server-dir: www/cliente1/ # Replace with your correct path
          protocol: ftps
          timeout: 86400000
          log-level: standard
          exclude: |
           .git/**
           .github/**
